package com.reals.app.notifications

object PushNotificationContract {
    const val TYPE_VISUAL_REVIEW_AVAILABLE = "VISUAL_REVIEW_AVAILABLE"
    const val TYPE_VISUAL_REVIEW_REMINDER = "VISUAL_REVIEW_REMINDER"
    const val TYPE_SCHEDULING_AVAILABLE = "SCHEDULING_AVAILABLE"
    const val TYPE_SCHEDULING_PROPOSALS_RECEIVED = "SCHEDULING_PROPOSALS_RECEIVED"
    const val TYPE_SCHEDULING_CONFIRMED = "SCHEDULING_CONFIRMED"
    const val TYPE_SECOND_CHAT_REMINDER = "SECOND_CHAT_REMINDER"
    const val TYPE_SECOND_CHAT_STARTED = "SECOND_CHAT_STARTED"

    const val EXTRA_PUSH_TYPE = "push_type"
    const val EXTRA_MATCH_ID = "match_id"
    const val EXTRA_CONNECTION_ID = "connection_id"
    const val EXTRA_AVAILABLE_AT = "available_at"
    const val EXTRA_REFRESH_HOME = "refresh_home"

    const val VISUAL_REVIEW_CHANNEL_ID = "visual_review"
    const val VISUAL_REVIEW_NOTIFICATION_ID_BASE = 10_000
    const val SCHEDULING_AVAILABLE_NOTIFICATION_ID_BASE = 15_000
    const val SECOND_CHAT_REMINDER_NOTIFICATION_ID_BASE = 20_000
}
